server:
  port: 7000
  servlet:
    context-path: /order

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hmily_order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: order-service

mybatis:
  type-aliases-package: com.zztr.hmilyorder.entity
  config-location: classpath:mybatis-config.xml

eureka:
  client:
    service-url:
      defaultZone: http://lzh:123456@127.0.0.1:8761/eureka/,http://lzh:123456@127.0.0.1:8762/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
