a:
  b:
    c: LiZanhong
    d: 2021

server:
  port: ${random.int[20000,80000]}

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    root: info