server:
  port: 7561
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7561/ppt-eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
spring:
  security:
    user:
      name: lzh
      password: 123456
  profiles:
    active: master